version: "3"
services:
  backend-dev:
    container_name: logistic_optimization
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    volumes:
      - ../:/app
      - ../instance/config.dev.py:/app/instance/config.py
    ports:
      - 5000:5000
